backend/core/urls.py
from django.urls import path

from .views import index

app_name = 'core'


urlpatterns = [
    path('', index, name='index'),
]

backend/crm/urls.py
from django.urls import include, path
from rest_framework import routers

from backend.crm import views as v
from backend.crm.api.viewsets import CustomerViewSet

app_name = 'crm'

router = routers.DefaultRouter()
router.register(r'customers', CustomerViewSet)

urlpatterns = [
    path('customer/', v.customer_list, name='customer_list'),
    path('employee/', v.employee_list, name='employee_list'),
    path('employee/create/', v.employee_create, name='employee_create'),
    path('api/', include(router.urls)),
]

backend/product/urls.py
from django.urls import path

from backend.product import views as v

app_name = 'product'


urlpatterns = [
    path('', v.product_type_list, name='product_type_list'),
]

backend/sale/urls.py
from django.urls import path

from backend.sale import views as v

app_name = 'sale'


urlpatterns = [
    path('', v.sale_list, name='sale_list'),
]

backend/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('backend.core.urls')),
    path('crm/', include('backend.crm.urls')),
    path('sale/', include('backend.sale.urls')),
    path('product/', include('backend.product.urls')),
    path('admin/', admin.site.urls),
]

backend/company/models.py
from django.db import models

from backend.tenant.models import Client


class Company(models.Model):
    name = models.CharField('nome', max_length=100, unique=True)
    cnpj = models.CharField('CNPJ', max_length=14, unique=True, null=True, blank=True)
    client = models.OneToOneField(
        Client,
        on_delete=models.CASCADE,
        verbose_name='cliente',
        related_name='companies',
    )

    class Meta:
        ordering = ('name',)
        verbose_name = 'empresa'
        verbose_name_plural = 'empresas'

    def __str__(self):
        return f'{self.name}'

backend/crm/models.py
from django.contrib.auth.models import User
from django.db import models


class Customer(models.Model):
    name = models.CharField('nome', max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'cliente'
        verbose_name_plural = 'clientes'

    def __str__(self):
        return f'{self.name}'


class Employee(models.Model):
    occupation = models.CharField('cargo', max_length=30, null=True, blank=True)
    cpf = models.CharField('CPF', max_length=11, null=True, blank=True)
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        verbose_name='usuário',
        related_name='employees',
    )

    class Meta:
        ordering = ('user__first_name',)
        verbose_name = 'funcionário'
        verbose_name_plural = 'funcionários'

    def __str__(self):
        return f'{self.user.get_full_name()}'

backend/product/models.py
from django.db import models


class ProductType(models.Model):
    title = models.CharField('título', max_length=100, unique=True)

    class Meta:
        ordering = ('title',)
        verbose_name = 'tipo de produto'
        verbose_name_plural = 'tipos de produtos'

    def __str__(self):
        return f'{self.title}'

backend/sale/models.py
from django.db import models

from backend.crm.models import Customer, Employee


class Sale(models.Model):
    title = models.CharField('título', max_length=30)
    customer = models.ForeignKey(
        Customer,
        on_delete=models.SET_NULL,
        verbose_name='cliente',
        related_name='customer_sales',
        null=True,
        blank=True
    )
    employee = models.ForeignKey(
        Employee,
        on_delete=models.SET_NULL,
        verbose_name='vendedor',
        related_name='employees_sales',
        null=True,
        blank=True
    )
    created = models.DateTimeField(
        'criado em',
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        ordering = ('title',)
        verbose_name = 'venda'
        verbose_name_plural = 'vendas'

    def __str__(self):
        return f'{self.title}'

backend/crm/forms.py
from django import forms

from .models import Employee


class EmployeeForm(forms.ModelForm):
    required_css_class = 'required'

    username = forms.CharField(
        label='Usuário',
        max_length=150,
    )
    first_name = forms.CharField(
        label='Nome',
        max_length=150,
    )
    last_name = forms.CharField(
        label='Sobrenome',
        max_length=150,
        required=False,
    )
    email = forms.EmailField(
        label='E-mail',
        required=False,
    )

    class Meta:
        model = Employee
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'occupation',
            'cpf',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'input mb-3'

backend/core/views.py
from django.shortcuts import render

from backend.crm.models import Customer, Employee
from backend.product.models import ProductType
from backend.sale.models import Sale

from django_tenants.utils import schema_context


@schema_context("public")
def product_types_all():

    return list(ProductType.objects.all().values())


def index(request):
    template_name = 'index.html'
    customers = Customer.objects.all()
    employees = Employee.objects.all()
    sales = Sale.objects.all()
    product_types = ProductType.objects.all()
    public_product_types = product_types_all()

    context = {
        'customers': customers,
        'employees': employees,
        'sales': sales,
        'product_types': product_types,
        'public_product_types': public_product_types,
    }
    return render(request, template_name, context)

backend/crm/views.py
from django.db.models import Q
from django.contrib.auth.models import User
from django.shortcuts import redirect, render

from .forms import EmployeeForm
from .models import Customer, Employee


def create_new_user(form):
    # Cria o Usuário.
    user = User.objects.create(
        username=form.cleaned_data['username'],
        first_name=form.cleaned_data['first_name'],
        last_name=form.cleaned_data['last_name'],
        email=form.cleaned_data['email'],
    )
    return user


def create_new_employee(form, user):
    # Cria o Funcionário.
    Employee.objects.create(
        occupation=form.cleaned_data['occupation'],
        cpf=form.cleaned_data['cpf'],
        user=user,
    )


def employee_create(request):
    template_name = 'crm/employee_form.html'
    form = EmployeeForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            form.save(commit=False)
            user = create_new_user(form)
            create_new_employee(form, user)
            # return HttpResponse('OK')
            return redirect('crm:employee_list')

    context = {'form': form}
    return render(request, template_name, context)


def customer_list(request):
    template_name = 'crm/customer_list.html'
    object_list = Customer.objects.all()
    context = {'object_list': object_list}
    return render(request, template_name, context)


def employee_list(request):
    template_name = 'crm/employee_list.html'
    object_list = Employee.objects.all()

    search = request.GET.get('search')
    if search:
        object_list = Employee.objects.filter(
            Q(user__first_name__icontains=search) |
            Q(user__last_name__icontains=search) |
            Q(occupation__icontains=search)
        )

    context = {'object_list': object_list}
    return render(request, template_name, context)

backend/product/views.py
from django.shortcuts import render

from .models import ProductType


def product_type_list(request):
    template_name = 'product/product_type_list.html'
    object_list = ProductType.objects.all()
    context = {'object_list': object_list}
    return render(request, template_name, context)

backend/sale/views.py
from django.shortcuts import render

from .models import Sale


def sale_list(request):
    template_name = 'sale/sale_list.html'
    object_list = Sale.objects.all()
    context = {'object_list': object_list}
    return render(request, template_name, context)

backend/core/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="shortcut icon" href="http://html5-training-in-hyderabad.blogspot.com.br/favicon.ico">
    <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
    <title>Django Tenant</title>

    <!-- Bulma -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
  </head>
  <body>

    <div class="container is-fluid">
      <div class="notification is-primary">
        <h1 class="title"><b>{{ request.tenant.name }}</b></h1>
      </div>
      {% block content %}{% endblock content %}
    </div>
  </body>
</html>

backend/core/templates/index.html
{% extends "base.html" %}

{% block content %}
  <div class="columns">
    <div class="column">
      <h1 class="title">
        <a href="{% url 'crm:customer_list' %}">Clientes</a>
      </h1>
      <ul>
        {% for customer in customers %}
          <li>{{ customer }}</li>
        {% endfor %}
      </ul>
    </div>
    <div class="column">
      <h1 class="title">
        <a href="{% url 'crm:employee_list' %}">Funcionários</a>
      </h1>
      <ul>
        {% for employee in employees %}
          <li>{{ employee }}</li>
        {% endfor %}
      </ul>
    </div>
    <div class="column">
      <h1 class="title">
        <a href="{% url 'sale:sale_list' %}">Vendas</a>
      </h1>
      <ul>
        {% for sale in sales %}
          <li>{{ sale }}</li>
        {% endfor %}
      </ul>
    </div>
    <div class="column">
      <h1 class="title">
        <a href="{% url 'product:product_type_list' %}">Tipos de Produtos</a>
      </h1>
      <ul>
        {% for product in product_types %}
          <li>{{ product }}</li>
        {% endfor %}
      </ul>
    </div>
    <div class="column">
      <h1 class="title">
        <a href="{% url 'product:product_type_list' %}">Tipos de Produtos</a>
      </h1>
      <ul>
        {% for product in public_product_types %}
          <li>{{ product }}</li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock content %}

backend/crm/templates/crm/customer_list.html
{% extends "base.html" %}

{% block content %}
  <h1 class="title">Clientes
    <a href="{% url 'core:index' %}">
      <small>Voltar</small>
    </a>
  </h1>
  <table class="table">
    <thead>
      <tr>
        <th>Nome</th>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list %}
        <tr>
          <td>{{ object }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

backend/crm/templates/crm/employee_form.html
{% extends "base.html" %}

{% block content %}
  <div class="columns is-mobile is-centered">
    <div class="column is-half">
      <form action="." method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button is-primary mt-3" type="submit">Salvar</button>
      </form>
    </div>
  </div>
{% endblock content %}

backend/crm/templates/crm/employee_list.html
{% extends "base.html" %}

{% block content %}
  <h1 class="title">Funcionários
    <a href="{% url 'core:index' %}">
      <small>Voltar</small>
    </a>
    <a class="button is-primary" href="{% url 'crm:employee_create' %}">Adicionar</a>
  </h1>

  <div class="columns ml-0">
    <div class="is-half">
      <form action="" method="GET">
        <div class="field has-addons">
          <div class="control">
            <input class="input" type="text" name="Search" placeholder="Buscar...">
          </div>
          <div class="control">
            <a class="button is-info">
              Buscar
            </a>
          </div>
        </div>
      </form>
    </div>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Cargo</th>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list %}
        <tr>
          <td>{{ object }}</td>
          <td>{{ object.occupation|default:"" }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

backend/product/templates/product/product_type_list.html
{% extends "base.html" %}

{% block content %}
  <h1 class="title">Tipos de Produtos
    <a href="{% url 'core:index' %}">
      <small>Voltar</small>
    </a>
  </h1>
  <table class="table">
    <thead>
      <tr>
        <th>Título</th>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list %}
        <tr>
          <td>{{ object }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}

backend/sale/templates/sale/sale_list.html
{% extends "base.html" %}

{% block content %}
  <h1 class="title">Vendas
    <a href="{% url 'core:index' %}">
      <small>Voltar</small>
    </a>
  </h1>
  <table class="table">
    <thead>
      <tr>
        <th>Título</th>
        <th>Data</th>
        <th>Cliente</th>
        <th>Funcionário</th>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list %}
        <tr>
          <td>{{ object.title }}</td>
          <td>{{ object.created|date:"d/m/Y" }}</td>
          <td>{{ object.customer }}</td>
          <td>{{ object.employee }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock content %}